### ISSUE TITLE
I'm new to b1.7.3 modding, and want to use Apron!

### ISSUE THREAD

**Issue by Bleb1k** [BetterThanUpdates/apron#39]
Hello!
I need help in setting up workspace for modding

I have installed vscode with few extensions for java developing, and tried to configure workspace with [this](https://github.com/ModificationStation/StationAPI/wiki/Configuring-your-Workspace) guide, but hit a gradle build error

**Comment by Bleb1k** [comment]
https://discord.com/channels/397834523028488203/397839387465089054/1034584641224581130
Advantages:
1. Modern toolchain (the entire modern Fabric toolchain except for FabricAPI which StationAPI replaces)
2. No need to port mods to server, since the development workspace is merged. The compiled mod jar works on both ends, too.
3. Way better compatibility between mods, since the only way to inject into the game is mixins, so you can't do base edits.
4. StationAPI uses a different world save format and different network packets, allowing for infinite item, entity and block IDs, as well as custom world height and bottom Y for dimensions.
5. StationAPI also does major changes to the rendering engine, allowing for modern BlockBench models to be used natively by items and blocks, as well as some other nice things like dynamic model renderer, infinite block and item texture sprites with any resolution, and shader support (not optifine shaders). This rewrite also utilizes some modern OpenGL functionality, which for me personally added extra 70 FPS on top of vanilla.

Disadvantages:
1. Incompatible with all the legacy modding stuff (Apron does make it more compatible, but, ideally, the mods should be ported).
2. Is a very large project and, recently, not so actively developed (the current update is already 2 years in development, with only 2 pre releases so far).
3. Isn't compatible with vanilla worlds and servers currently. A converter from and to stapi's format will be created later.

**Comment by Bleb1k** [comment]
Basically all all advantages listed here is why I want to use it

**Comment by halotroop2288** [comment]
Posting Discord message links is generally a bad idea unless it's the official server for the project.

I still maintain that it's a bad idea to depend on Apron, as it will cause issues. Legacy mods need to be ported to Babric to be fully compatible with new mods.

What are those disadvantages listed for? Certainly not Apron. It is in active development by @arthurbambou and hasn't even been around for 2 years.

Finally, since Apron is still in active development, there may be changes that break your code at any time without warning.
